.TH "Button" 6 "27 August 2018" "Version 1.241" "On The Subject of The Button"

.SH SYNOPSIS

.I You might think that a button telling you to press it is pretty straightforward.

.I That’s the kind of thinking that gets people exploded.

.SH DESCRIPTION

Follow these rules in the order they are listed. Perform the first action that applies

.nr step 1 1
.IP \n[step].
If the button is blue and the button says "Abort", hold the button and refer to 
.I Releasing a Held Button.
.IP \n+[step].
If there is more than 1 battery on the bomb and the button says "Detonate", press and immediately release the button.
.IP \n+[step].
If the button is white and there is a lit indicator with label CAR, hold the button and refer to
.I Releasing a Held Button.
.IP \n+[step].
If there are more than 2 batteries on the bomb and there is a lit indicator with label FRK, press and immediately release the button.
.IP \n+[step].
If the button is yellow, hold the button and refer to
.I Releasing a Held Button.
.IP \n+[step].
If the button is red and the button says "Hold", press and immediately release the button.
.IP \n+[step].
If none of the above apply, hold the button and refer to
.I Releasing a Held Button.

.SH Releasing a Held Button 
If you start holding the button down, a colored strip will light up on the right side of the module.
Based on its color you must release the button at a specific point in time:

\(bu Blue strip: release when the countdown timer has a 4 in any position.

\(bu White strip: release when the countdown timer has a 1 in any position.

\(bu Yellow strip: release when the countdown timer has a 5 in any position.

\(bu Any other color strip: release when the countdown timer has a 1 in any position.
